name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]
          uv pip install pre-commit

      - name: Setup Docker for hadolint
        run: docker pull hadolint/hadolint:v2.12.0

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]

      - name: Run ruff check (linter)
        run: uv run ruff check src/ tests/

      - name: Run ruff format check (formatter)
        run: uv run ruff format --check src/ tests/

      - name: Run tests
        run: uv run pytest --no-cov -q

      - name: Run type checking with mypy
        run: uv run mypy src/
        continue-on-error: true
